from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 331)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("proekt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_comma = QtWidgets.QPushButton(self.centralwidget)
        self.bt_comma.setGeometry(QtCore.QRect(20, 260, 51, 41))
        self.bt_comma.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.bt_comma.setObjectName("bt_comma")
        self.bt_zero = QtWidgets.QPushButton(self.centralwidget)
        self.bt_zero.setGeometry(QtCore.QRect(80, 260, 51, 41))
        self.bt_zero.setObjectName("bt_zero")
        self.bt_equals = QtWidgets.QPushButton(self.centralwidget)
        self.bt_equals.setGeometry(QtCore.QRect(140, 260, 51, 41))
        self.bt_equals.setObjectName("bt_equals")
        self.bt_one = QtWidgets.QPushButton(self.centralwidget)
        self.bt_one.setGeometry(QtCore.QRect(20, 210, 51, 41))
        self.bt_one.setObjectName("bt_one")
        self.bt_two = QtWidgets.QPushButton(self.centralwidget)
        self.bt_two.setGeometry(QtCore.QRect(80, 210, 51, 41))
        self.bt_two.setObjectName("bt_two")
        self.bt_three = QtWidgets.QPushButton(self.centralwidget)
        self.bt_three.setGeometry(QtCore.QRect(140, 210, 51, 41))
        self.bt_three.setObjectName("bt_three")
        self.bt_four = QtWidgets.QPushButton(self.centralwidget)
        self.bt_four.setGeometry(QtCore.QRect(20, 160, 51, 41))
        self.bt_four.setObjectName("bt_four")
        self.bt_five = QtWidgets.QPushButton(self.centralwidget)
        self.bt_five.setGeometry(QtCore.QRect(80, 160, 51, 41))
        self.bt_five.setObjectName("bt_five")
        self.bt_six = QtWidgets.QPushButton(self.centralwidget)
        self.bt_six.setGeometry(QtCore.QRect(140, 160, 51, 41))
        self.bt_six.setObjectName("bt_six")
        self.bt_seven = QtWidgets.QPushButton(self.centralwidget)
        self.bt_seven.setGeometry(QtCore.QRect(20, 110, 51, 41))
        self.bt_seven.setObjectName("bt_seven")
        self.bt_eight = QtWidgets.QPushButton(self.centralwidget)
        self.bt_eight.setGeometry(QtCore.QRect(80, 110, 51, 41))
        self.bt_eight.setObjectName("bt_eight")
        self.bt_nine = QtWidgets.QPushButton(self.centralwidget)
        self.bt_nine.setGeometry(QtCore.QRect(140, 110, 51, 41))
        self.bt_nine.setObjectName("bt_nine")
        self.bt_inf = QtWidgets.QPushButton(self.centralwidget)
        self.bt_inf.setGeometry(QtCore.QRect(260, 110, 51, 31))
        self.bt_inf.setObjectName("bt_inf")
        self.bt_sin = QtWidgets.QPushButton(self.centralwidget)
        self.bt_sin.setGeometry(QtCore.QRect(260, 150, 51, 31))
        self.bt_sin.setObjectName("bt_sin")
        self.bt_in = QtWidgets.QPushButton(self.centralwidget)
        self.bt_in.setGeometry(QtCore.QRect(260, 190, 51, 31))
        self.bt_in.setObjectName("bt_in")
        self.bt_pi = QtWidgets.QPushButton(self.centralwidget)
        self.bt_pi.setGeometry(QtCore.QRect(260, 230, 51, 31))
        self.bt_pi.setObjectName("bt_pi")
        self.bt_bracket1 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_bracket1.setGeometry(QtCore.QRect(260, 270, 51, 31))
        self.bt_bracket1.setObjectName("bt_bracket1")
        self.bt_log = QtWidgets.QPushButton(self.centralwidget)
        self.bt_log.setGeometry(QtCore.QRect(320, 190, 51, 31))
        self.bt_log.setObjectName("bt_log")
        self.bt_cos = QtWidgets.QPushButton(self.centralwidget)
        self.bt_cos.setGeometry(QtCore.QRect(320, 150, 51, 31))
        self.bt_cos.setObjectName("bt_cos")
        self.bt_bracket2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt_bracket2.setGeometry(QtCore.QRect(320, 270, 51, 31))
        self.bt_bracket2.setObjectName("bt_bracket2")
        self.bt_e = QtWidgets.QPushButton(self.centralwidget)
        self.bt_e.setGeometry(QtCore.QRect(320, 230, 51, 31))
        self.bt_e.setObjectName("bt_e")
        self.bt_deg = QtWidgets.QPushButton(self.centralwidget)
        self.bt_deg.setGeometry(QtCore.QRect(320, 110, 51, 31))
        self.bt_deg.setObjectName("bt_deg")
        self.bt_exclamationPoint = QtWidgets.QPushButton(self.centralwidget)
        self.bt_exclamationPoint.setGeometry(QtCore.QRect(380, 190, 51, 31))
        self.bt_exclamationPoint.setObjectName("bt_exclamationPoint")
        self.bt_tan = QtWidgets.QPushButton(self.centralwidget)
        self.bt_tan.setGeometry(QtCore.QRect(380, 150, 51, 31))
        self.bt_tan.setObjectName("bt_tan")
        self.bt_radix = QtWidgets.QPushButton(self.centralwidget)
        self.bt_radix.setGeometry(QtCore.QRect(380, 270, 51, 31))
        self.bt_radix.setObjectName("bt_radix")
        self.bt_degree = QtWidgets.QPushButton(self.centralwidget)
        self.bt_degree.setGeometry(QtCore.QRect(380, 230, 51, 31))
        self.bt_degree.setObjectName("bt_degree")
        self.bt_percent = QtWidgets.QPushButton(self.centralwidget)
        self.bt_percent.setGeometry(QtCore.QRect(380, 110, 51, 31))
        self.bt_percent.setObjectName("bt_percent")
        self.bt_multiplication = QtWidgets.QPushButton(self.centralwidget)
        self.bt_multiplication.setGeometry(QtCore.QRect(200, 190, 51, 31))
        self.bt_multiplication.setObjectName("bt_multiplication")
        self.bt_division = QtWidgets.QPushButton(self.centralwidget)
        self.bt_division.setGeometry(QtCore.QRect(200, 150, 51, 31))
        self.bt_division.setObjectName("bt_division")
        self.bt_minus = QtWidgets.QPushButton(self.centralwidget)
        self.bt_minus.setGeometry(QtCore.QRect(200, 230, 51, 31))
        self.bt_minus.setObjectName("bt_minus")
        self.bt_plus = QtWidgets.QPushButton(self.centralwidget)
        self.bt_plus.setGeometry(QtCore.QRect(200, 270, 51, 31))
        self.bt_plus.setObjectName("bt_plus")
        self.bt_del = QtWidgets.QPushButton(self.centralwidget)
        self.bt_del.setGeometry(QtCore.QRect(200, 110, 51, 31))
        self.bt_del.setObjectName("bt_del")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 461, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(169, 166, 170);\n""color: rgb(255, 255, 255);")
        self.label_result.setTextFormat(QtCore.Qt.AutoText)
        self.label_result.setScaledContents(False)
        self.label_result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_result.setWordWrap(False)
        self.label_result.setIndent(-1)
        self.label_result.setOpenExternalLinks(False)
        self.label_result.setObjectName("label_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.bt_comma.setText(_translate("MainWindow", ","))
        self.bt_zero.setText(_translate("MainWindow", "0"))
        self.bt_equals.setText(_translate("MainWindow", "="))
        self.bt_one.setText(_translate("MainWindow", "1"))
        self.bt_two.setText(_translate("MainWindow", "2"))
        self.bt_three.setText(_translate("MainWindow", "3"))
        self.bt_four.setText(_translate("MainWindow", "4"))
        self.bt_five.setText(_translate("MainWindow", "5"))
        self.bt_six.setText(_translate("MainWindow", "6"))
        self.bt_seven.setText(_translate("MainWindow", "7"))
        self.bt_eight.setText(_translate("MainWindow", "8"))
        self.bt_nine.setText(_translate("MainWindow", "9"))
        self.bt_inf.setText(_translate("MainWindow", "INF"))
        self.bt_sin.setText(_translate("MainWindow", "sin"))
        self.bt_in.setText(_translate("MainWindow", "ln"))
        self.bt_pi.setText(_translate("MainWindow", "PI"))
        self.bt_bracket1.setText(_translate("MainWindow", "("))
        self.bt_log.setText(_translate("MainWindow", "log"))
        self.bt_cos.setText(_translate("MainWindow", "cos"))
        self.bt_bracket2.setText(_translate("MainWindow", ")"))
        self.bt_e.setText(_translate("MainWindow", "e"))
        self.bt_deg.setText(_translate("MainWindow", "DEG"))
        self.bt_exclamationPoint.setText(_translate("MainWindow", "!"))
        self.bt_tan.setText(_translate("MainWindow", "tan"))
        self.bt_radix.setText(_translate("MainWindow", "√"))
        self.bt_degree.setText(_translate("MainWindow", "^"))
        self.bt_percent.setText(_translate("MainWindow", "%"))
        self.bt_multiplication.setText(_translate("MainWindow", "*"))
        self.bt_division.setText(_translate("MainWindow", "/"))
        self.bt_minus.setText(_translate("MainWindow", "-"))
        self.bt_plus.setText(_translate("MainWindow", "+"))
        self.bt_del.setText(_translate("MainWindow", "DEL"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
